version: '3.8'

services:
  mbira-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbira-hub
    restart: unless-stopped
    ports:
      - "9445:8445"  # HTTPS
      - "9767:8767"  # WebSocket
    volumes:
      - ./data:/app/data
      - ./certs:/app/certs
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=8445
      - WS_PORT=8767
      - DATA_DIR=/app/data
      - MASTER_PASSWORD=${MASTER_PASSWORD}
      - DOMAIN=${DOMAIN:-localhost}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - mbira-network
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8445/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  redis:
    image: redis:7-alpine
    container_name: mbira-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - mbira-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

volumes:
  redis-data:
    driver: local

networks:
  mbira-network:
    driver: bridge
